/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/views/**/*.hbs',
    './src/public/js/**/*.js',
    './dist/views/**/*.hbs',
    './dist/public/js/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      boxShadow: {
        soft: '0 1px 2px 0 rgb(0 0 0 / 0.04), 0 1px 3px 0 rgb(0 0 0 / 0.06)',
        lift: '0 12px 32px -12px rgb(0 0 0 / 0.25)',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        admindb: {
          primary: '#6d5df6',
          'primary-content': '#ffffff',
          secondary: '#0ea5e9',
          'secondary-content': '#ffffff',
          accent: '#10b981',
          'accent-content': '#052e1f',
          neutral: '#171923',
          'neutral-content': '#e7e9ee',
          'base-100': '#ffffff',
          'base-200': '#f4f5f8',
          'base-300': '#e5e7ee',
          'base-content': '#232739',
          info: '#3b82f6',
          'info-content': '#eaf2ff',
          success: '#10b981',
          'success-content': '#052e1f',
          warning: '#f59e0b',
          'warning-content': '#3b2300',
          error: '#ef4444',
          'error-content': '#ffffff',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.6rem',
          '--rounded-badge': '1.9rem',
          '--border-btn': '1px',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.2s',
        },
      },
      {
        admindbDark: {
          primary: '#8b7cf8',
          'primary-content': '#14121f',
          secondary: '#38bdf8',
          'secondary-content': '#062233',
          accent: '#34d399',
          'accent-content': '#052e22',
          neutral: '#0a0c11',
          'neutral-content': '#e7e9ee',
          'base-100': '#0e1016',
          'base-200': '#14161f',
          'base-300': '#1d2029',
          'base-content': '#e7e9ee',
          info: '#60a5fa',
          'info-content': '#0b1e3a',
          success: '#34d399',
          'success-content': '#052e22',
          warning: '#fbbf24',
          'warning-content': '#3b2300',
          error: '#f87171',
          'error-content': '#2c0a0a',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.6rem',
          '--rounded-badge': '1.9rem',
          '--border-btn': '1px',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.2s',
        },
      },
    ],
    logs: false,
  },
};
