/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/views/**/*.hbs',
    './src/public/js/**/*.js',
    './dist/views/**/*.hbs',
    './dist/public/js/**/*.js',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headings: ['"Sora"', '"IBM Plex Sans"', 'ui-sans-serif', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      boxShadow: {
        soft: '0 1px 2px 0 rgb(0 0 0 / 0.04), 0 1px 3px 0 rgb(0 0 0 / 0.06)',
        card: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
        teal: '0 10px 15px -3px rgba(15, 118, 110, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.04)',
        lift: '0 12px 34px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        admindb: {
          primary: '#0f766e',
          'primary-content': '#ffffff',
          secondary: '#1f8f84',
          'secondary-content': '#ffffff',
          accent: '#10b981',
          'accent-content': '#052e1f',
          neutral: '#1f2a2a',
          'neutral-content': '#e2ede8',
          'base-100': '#ffffff',
          'base-200': '#f4f7f3',
          'base-300': '#dce8e3',
          'base-content': '#1f2a2a',
          info: '#0284c7',
          'info-content': '#eaf2ff',
          success: '#16a34a',
          'success-content': '#ffffff',
          warning: '#d97706',
          'warning-content': '#ffffff',
          error: '#dc2626',
          'error-content': '#ffffff',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--border-btn': '1px',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.2s',
        },
      },
      {
        admindbDark: {
          primary: '#14b8a6',
          'primary-content': '#042f2c',
          secondary: '#2dd4bf',
          'secondary-content': '#042f2c',
          accent: '#34d399',
          'accent-content': '#042f2c',
          neutral: '#0b1716',
          'neutral-content': '#e2ede8',
          'base-100': '#112220',
          'base-200': '#0a1413',
          'base-300': '#193834',
          'base-content': '#e6f4f1',
          info: '#38bdf8',
          'info-content': '#04273a',
          success: '#34d399',
          'success-content': '#042f2c',
          warning: '#fbbf24',
          'warning-content': '#2d1b00',
          error: '#f87171',
          'error-content': '#3a0808',
          '--rounded-box': '1rem',
          '--rounded-btn': '0.5rem',
          '--rounded-badge': '1.9rem',
          '--border-btn': '1px',
          '--tab-radius': '0.5rem',
          '--animation-btn': '0.15s',
          '--animation-input': '0.2s',
        },
      },
    ],
    logs: false,
  },
};
